### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by bobcate** [lucyknada/sillytavern-youtube-summary#5]
Is this extension still working?
- First, I had to use [this extension](https://chromewebstore.google.com/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf) because something about not being able to call out from localhost,
- then I had to use a VPN because CloudFlare was blocking my access to corsproxy.io,
- finally I got this error:
![image](https://github.com/lucyknada/sillytavern-youtube-summary/assets/34423403/d8680814-1569-4465-8d1f-89064d73776b)

**Comment by bobcate** [comment]
The https://github.com/SillyTavern/SillyTavern/commit/43f52d5436ad2ad2f955a1e127445f802a2ea7ee update made it possible to scrape Youtube transcriptions with `/yt-script` command.

**Comment by lucyknada** [comment]
yep seems like youtube broke the old endpoint again.

the actually relevant part of the linked changes: https://github.com/SillyTavern/SillyTavern/blob/1d32749ed26a6d2916f5b1b98380019c50215d0b/src/endpoints/serpapi.js#L55-L135

I'll fix it when I have the time.

**Comment by lucyknada** [comment]
I decided I had the time :)

**Comment by lucyknada** [comment]
another update, because youtube seems to prevent external cors proxies now; instead of writing my own server plugin, it now simply wraps ST's own built-in server endpoint for the transcript, should work for the forseeable future.
